---
# vars file for osp.servers
osp_servers:
#  - type: frontend
  - name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: frontend
    network: int_network
    meta:
      - group: frontends 
      - deployment_name: QA
#  - type:  app1
  - name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    network: int_network
    meta:
      - group: apps 
      - deployment_name: QA
#  - type:   app2
  - name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    network: int_network
    meta:
      - group: apps 
      - deployment_name: QA
#  - type:   db
  - name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: db
    network: int_network
    meta:
      - group: appdbs 
      - deployment_name: QA
