---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    cloud: ospcloud
    state: present
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    key_name: "{{ item.key_name }}"
    flavor: "{{ item.flavor }}"
    security_groups: "{{ item.security_groups }}"
#    meta: "group={{ group }},deployment_name={{ deployment_name }}"
  loop: os_server

#- name: Add floating IP to Servers
#  os_floating_ip:
#    cloud: ospcloud
#    state: present
#    reuse: yes
    

#- name: Wait for server to be available
